# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88df979925a69ac0c80ad7a7976b4f786e828bca9dab38cffe01dbc19d72af6ecec9ea2fedd1428db6fb2333c32dd7774833fd55a7741aae50b6072598bd1dae

test:
  secret_key_base: 3b4179ef1229d04a1e402bb8c69d612d29f76a206d9974288c2150db0b4882504580d78f007b7880488adddd5d3408e2cfcd9d54d9353a2c23592b4694c98cf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
